spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/jiheiwu?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
#mybatis:
#  type-aliases-package: com.socket.test.socketdemo.dao

setting:
  gold: 10 #注册赠送金币
  create-gold: 10 #每局消费金币
server:
  port: 80